/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import colegioData.Alumnodata;
import javax.swing.JOptionPane;
import laboratoriotp4grupo4.Alumno;

/**
 *
 * @author canes
 */
public class FormularioAlumno extends javax.swing.JInternalFrame{
   protected static Alumnodata alum;
   
    
    public FormularioAlumno() {
        initComponents();
        desactivarCampos();
        alum= new Alumnodata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfSalirFA = new javax.swing.JButton();
        jfApellido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jfLegajo = new javax.swing.JTextField();
        jfNombre = new javax.swing.JTextField();
        jfNuevoFA = new javax.swing.JButton();
        jfGuardar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("FAlumnos");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jfSalirFA.setText("Salir");
        jfSalirFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfSalirFAActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulario de Alumnos");

        jLabel2.setText("Legajo:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Nombre:");

        jfLegajo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jfLegajoFocusLost(evt);
            }
        });
        jfLegajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfLegajoActionPerformed(evt);
            }
        });

        jfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfNombreActionPerformed(evt);
            }
        });

        jfNuevoFA.setText("Nuevo");
        jfNuevoFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfNuevoFAActionPerformed(evt);
            }
        });

        jfGuardar.setText("Guardar");
        jfGuardar.setEnabled(false);
        jfGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jfApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(jfLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jfNombre)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jfSalirFA)
                        .addGap(101, 101, 101)
                        .addComponent(jfNuevoFA)
                        .addGap(27, 27, 27)
                        .addComponent(jfGuardar)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jfLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfNuevoFA)
                    .addComponent(jfSalirFA)
                    .addComponent(jfGuardar))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void jfSalirFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfSalirFAActionPerformed
  dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jfSalirFAActionPerformed

    private void jfLegajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfLegajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfLegajoActionPerformed

    private void jfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfNombreActionPerformed

    private void jfNuevoFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfNuevoFAActionPerformed
          limpiarCampos();
        activarCampos();
        jfGuardar.setEnabled(true);
    }//GEN-LAST:event_jfNuevoFAActionPerformed

    private void jfGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfGuardarActionPerformed
 Alumno al= new Alumno();
 
        if (jfNombre.getText().length()==0){
             JOptionPane.showMessageDialog(this,"Debe ingresar un Nombre ");
            jfNombre.requestFocus();   
  } else{
            if(0==jfApellido.getText().length()){
             JOptionPane.showMessageDialog(this,"Debe ingresar un Apellido ");
            jfApellido.requestFocus();   
  }else{  try {      
       al.setLegajo(Integer.parseInt(jfLegajo.getText()));
       al.setNombre(jfNombre.getText());
       al.setApellido(jfApellido.getText());
        alum.guardarAlumno(al);
      
      }
      catch(Exception e){
              
              JOptionPane.showMessageDialog(this,"ERROR - No ha llenado correctamente los campos");
              
              }
      
      limpiarCampos();
   
          }
    }//GEN-LAST:event_jfGuardarActionPerformed
    }
      public void limpiarCampos(){
    jfApellido.setText("");
    jfLegajo.setText("");
    jfNombre.setText("");
    desactivarCampos();
    jfGuardar.setEnabled(false);
}

    private void jfLegajoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jfLegajoFocusLost
           String value="[0-9]*";
      
        if (!jfLegajo.getText().matches(value)){
          
            JOptionPane.showMessageDialog(this,"ERROR - Solo números");
            jfLegajo.requestFocus();
    }                                  
    
    }//GEN-LAST:event_jfLegajoFocusLost
    
   
           private void activarCampos() {
        
        jfLegajo.setEnabled(true);
        jfApellido.setEnabled(true);
        jfNombre.setEnabled(true);
    
    }
    
     
    private void desactivarCampos() {
    
        jfLegajo.  setEnabled(false);
        jfApellido.setEnabled(false);
        jfNombre.setEnabled(false);
        
        
    } 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jfApellido;
    private javax.swing.JButton jfGuardar;
    private javax.swing.JTextField jfLegajo;
    private javax.swing.JTextField jfNombre;
    private javax.swing.JButton jfNuevoFA;
    private javax.swing.JButton jfSalirFA;
    // End of variables declaration//GEN-END:variables



}